### ISSUE TITLE
Removing theme from noDemo?

### ISSUE THREAD

**Issue by jpescador** [spf13/hugoThemeSiteScript#12]
Hello, can the future-imperfect theme be removed from the noDemo list now that the following issue has been resolved? https://github.com/spf13/hugo/issues/2005. Also referencing the temporary disable (29290829). Thanks.

**Comment by digitalcraftsman** [comment]
Hi @jpescador,

the issue is resolved. Currently, I don't have write access to this repository but I requested the rights.

**Comment by jpescador** [comment]
Thanks!
