### ISSUE TITLE
Support `demo` parameter in `theme.toml` for specifying custom demos

### ISSUE THREAD

**Issue by gcushen** [spf13/hugoThemeSiteScript#15]
On the Theme Showcase website, currently it's not possible to change a theme's *demo* button to point to a custom demo URL. Consider for example @bep's http://themes.gohugo.io/docuapi/ . He has added the theme to the *no demo* list in the Theme Showcase Script and pointed the **homepage** URL at his own **demo**. Surely, it would be better to consistently use the *demo* button for demos? Then the *homepage* button is free to point to the theme's homepage, e.g. Github repo.

I am in the position of wanting to change my Academic (http://themes.gohugo.io/academic/ ) theme's demo to point to a custom demo that does not use the `exampleSite` content, since Academic uses `exampleSite` as a starting configuration for new sites (so it's not the best place to add stuff that is specific to our Demo website). However, I believe it is confusing for users when the *demo* link is removed and *homepage* is used as *demo*. Users are likely to think that the theme **does not** have a demo available. Consistency is important. 

Really we should parse an optional `demo` parameter in a Theme's `theme.toml`, used for specifying custom demos, and update the script to check if it exists, and if so point to it.

**Comment by bep** [comment]
A big maybe ... The docuapi is just temporary until Steve gets Pygments installed on the themes server.

The way we have it today the demo has two functions:

1) A demo of how it looks / behaves
2) A demo/test that we can actually build it without too much problems with the latest Hugo version

Having the demos live on the outside of gohugo.io will maybe not encourage people to create robust themes with good demos/example site ...

**Comment by gcushen** [comment]
I understand that you are concerned with theme quality and compatibility.

I agree that external demos may encourage theme developers to not test against new versions of Hugo and hence could waste users' time downloading themes that don't work. Or developers could even deceive users (fake the screenshots etc.) and the user would not be aware until they attempted downloading and running the theme.

Perhaps taking an approach that gives results similar to continuous integration services could prevent these issues. For example:

1. ThemeSiteScript would remove themes from the Theme Showcase that fail against the latest stable Hugo build (and could even provide a green/red badge depending on if it passes/fails building against Hugo-dev).
2. For themes that are compatible, the script could then generate preview images of `screenshot-blurred` and `screenshot-container` that are using in the header of each theme's page on Theme Showcase website (this would be pretty trivial to implement in a language like Python).
3. A green badge (like the continuous integration ones) is shown on the theme's Theme Showcase page  to denote that the theme has passed the ThemeSiteScript build process
4. For themes using an external demo, a user can click on the badge and it will show the `exampleSite` built by ThemeSiteScript. This will allow the user to compare the ThemeSiteScript theme demo against the external demo provided by the theme dev, so they can minimise the risk of 

By automatically removing incompatible themes, showing screenshots generated by ThemeSiteScript (rather than those submitted by theme devs), and still providing a demo built by ThemeSiteScript by clicking the green *pass* badge, this would reduce the risk in allowing external demos. But yes, implementing and maintaining these measures would add a little extra work  :satisfied:

**Comment by bep** [comment]
>But yes, implementing and maintaining these measures would add a little extra work

Those are good ideas, but sounds like work with less priority than, say, getting a refurbished docs site up and running. 1) Could be implemented as a first pass, but I will have to think about it (see how many themes fall into this category).
