### ISSUE TITLE
Example site has invalid URLs if not prepended with .Site.BaseURL

### ISSUE THREAD

**Issue by chipsenkbeil** [spf13/hugoThemeSiteScript#5]
So, I wanted to check that the theme I just submitted worked correctly here. It appears that it does not as most of the URLs are invalid.

![screen shot 2015-09-30 at 8 23 02 am](https://cloud.githubusercontent.com/assets/2481802/10194103/80fa5508-674c-11e5-88ea-b89a9d6d63a6.png)

All of the images are not showing. Furthermore, if you click on a link, it takes you to http://localhost:1313/post/ instead of http://localhost:1313/theme/grid-side/post/. Going to http://localhost:1313/theme/grid-side/post/ manually works.

This is because I was allowing users to provide any URL in the front matter and config.toml, not just URLs to their own content. Because of this, I did not prepend `.Site.BaseURL` to most of my content (other than static Javascript/CSS). Is that what is required for a theme to work with the site generator? Are you guys setting the BaseURL for each site to be able to manage resources? I can go back through my theme and update all of those locations such that it works properly here, but I wanted to make sure.

[EDIT]
It would be useful to be able to test a custom theme locally using this script. My method was to copy the exampleSite directory out somewhere, provide a softlink to my theme, and then run `hugo server` locally. This worked for me because it was just hosting a single site with resources being at the root okay.

If I had been able to test this, I would have fixed the URLs (if it's a problem with not using .Site.BaseURL everywhere) before submitting my theme.

**Comment by bep** [comment]
> Are you guys setting the BaseURL for each site to be able to manage resources? 

Yes. But if you provide your own exampleSite, you must make sure you set `canonifyurls = true`; that should (no guarantees)  your problem.

As to improvements to script: PRs are welcome. I have spent too much time on this project already, without any visible result.

**Comment by chipsenkbeil** [comment]
Went back and added .Site.BaseURL to a variety of URLs to solve this problem.
