### ISSUE TITLE
Add scaling/compression to screenshots/thumbnails

### ISSUE THREAD

**Issue by bep** [spf13/hugoThemeSiteScript#7]
The site is live and looks great -- but (some of) the images are big and makes the site a little bit slower than it should.

/cc @spf13

**Comment by moorereason** [comment]
I've used [ImageMagick convert](http://www.imagemagick.org/script/command-line-processing.php#geometry) to do automated image resizing in the past.  Works great.

**Comment by bep** [comment]
@moorereason agree. We've tried to make the script "runnable by most people" by keeping it `bash`-- but `convert` *should* be installed on most serious people's *nix machines. Pull request for this is welcomed - then @spf13 can have a saying as to if his deployment rig is prepared or not.

**Comment by spf13** [comment]
I don't have convert installed on the VPS this is running/hosted on, but I probably can install it.

**Comment by digitalcraftsman** [comment]
@bep is this still an issue?

**Comment by bep** [comment]
Yes. But the issue should mabe be moved.

**Comment by digitalcraftsman** [comment]
@bep while browsing the dashboard for the theme site on Netlify I found an option to let Netlify compress the images automatically. Have a look at "asset optimization" section in the "settings" tab.

**Comment by bep** [comment]
The compression isn't the big problem here (but we should look into that, too); it is the people who add a 3000x3000 pixel image which we then present as a 100x100 thumbnail on the main page (I just took those values right out of the blue).

**Comment by digitalcraftsman** [comment]
Before adding themes to the list I also check the dimensions of the thumbnail but since users can change it afterwards I get your (exaggerated) example.

I'll move this issue now.

**Comment by digitalcraftsman** [comment]
Btw, I enabled image compression in the Netlify dashbaord for the theme site.
